export const CONTROLLER_ACTIONS = Object.freeze({
	UPDATE_NAME_INPUT: 'INPUT/UPDATE_NAME_VALUE',
	UPDATE_NAME_SCALE: 'NAME/UPDATE_NAME_SCALE',
	UPDATE_NAME_POSITIONS: 'NAME/UPDATE_NAME_POSITIONS',

	UPDATE_GUILD_INPUT: 'INPUT/UPDATE_GUILD_VALUE',
	UPDATE_GUILD_SCALE: 'GUILD/UPDATE_GUILD_SCALE',
	UPDATE_GUILD_POSITIONS: 'GUILD/UPDATE_GUILD_POSITIONS',
})